In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df_1 = pd.read_csv("../Raw_Data/Social_Engine_Users.csv")
df_1.head()

        `user_id          location language account_created  follower_count
0  user_guglt5jp   Berlin, Germany       ja      23-10-2023           38963
1  user_b1p3wz81   Munich, Germany       zh      06-05-2023           24644
2  user_jm2grmis        Dubai, UAE       en      03-01-2023           45842
3  user_ykoqww5l     Paris, France       fr      11-10-2023             665
4  user_3zzvv8vp  Los Angeles, USA       ru      23-05-2023           42908

In [3]:
df_2 = pd.read_csv("../Raw_Data/Social_Engine_Posts_Corrupted.csv")
df_2.head()

,post_id,user_id,platform,text_content,timestamp,likes,shares,comments
0,to64mgey2v3y,user_vfxs1pry,Reddit,Bummed out with my new Air Max from Nike! Abso...,25-09-2024,4488.0,1456,673
1,7f0wdauzbj89,user_8l7rv5oe,Reddit,My one month review of Pepsi Crystal Pepsi: Hi...,1722528840,789.0,1484,39
2,dvvhg8eel45x,user_nfo3ih5u,NaN,Just unboxed my new Highlander from Toyota. Ex...,2025-04-13T20:12:18,NaN,1410,839
3,hgb9cxke4t7b,user_27aje6ur,Facebook,Comparing Pepsi Crystal Pepsi to the competiti...,10-09-2024,167.0,584,833
4,zwerpw3wk320,user_9px5q0by,Reddit,My one week review of Coca-Cola Diet Coke: Bes...,31-05-2024,4749.0,152,630

In [4]:
df_1.shape

(1500, 5)

In [5]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   `user_id         1500 non-null   object
 1   location         1500 non-null   object
 2   language         1500 non-null   object
 3   account_created  1500 non-null   object
 4   follower_count   1500 non-null   int64
dtypes: int64(1), object(4)
memory usage: 58.7+ KB

In [6]:
df_1.rename(columns = {'`user_id':'user_id'}, inplace=True)

In [7]:
df_1.columns

Index(['user_id', 'location', 'language', 'account_created', 'follower_count'], dtype='object')

In [8]:
df_1['location'].unique()

array(['Berlin, Germany', 'Munich, Germany', 'Dubai, UAE',
       'Paris, France', 'Los Angeles, USA', 'Mumbai, India',
       'Rio de Janeiro, Brazil', 'Mexico City, Mexico',
       'Vancouver, Canada', 'London, UK', 'Houston, USA',
       'Manchester, UK', 'Seoul, South Korea',
       'Johannesburg, South Africa', 'São Paulo, Brazil', 'Osaka, Japan',
       'Rome, Italy', 'Barcelona, Spain', 'Shanghai, China',
       'Lagos, Nigeria', 'Tokyo, Japan', 'New York, USA',
       'Beijing, China', 'Melbourne, Australia', 'Lyon, France',
       'Madrid, Spain', 'Milan, Italy', 'Chicago, USA', 'Singapore',
       'Delhi, India', 'Sydney, Australia', 'Cairo, Egypt',
       'Toronto, Canada'], dtype=object)

In [9]:
## replacing 'Singapore' into  Cit,Country pair
df_1['location'].replace({'Singapore' : 'Singapore, Singapore'}, inplace=True)

In [10]:
df_1['language'].unique()

array(['ja', 'zh', 'en', 'fr', 'ru', 'es', 'de', 'ar', 'pt', 'hi'],
      dtype=object)

In [11]:
df_1.isnull().sum()

user_id            0
location           0
language           0
account_created    0
follower_count     0
dtype: int64

In [12]:
df_1.duplicated().sum()

0

In [13]:
df_2.head()

,post_id,user_id,platform,text_content,timestamp,likes,shares,comments
0,to64mgey2v3y,user_vfxs1pry,Reddit,Bummed out with my new Air Max from Nike! Abso...,25-09-2024,4488.0,1456,673
1,7f0wdauzbj89,user_8l7rv5oe,Reddit,My one month review of Pepsi Crystal Pepsi: Hi...,1722528840,789.0,1484,39
2,dvvhg8eel45x,user_nfo3ih5u,NaN,Just unboxed my new Highlander from Toyota. Ex...,2025-04-13T20:12:18,NaN,1410,839
3,hgb9cxke4t7b,user_27aje6ur,Facebook,Comparing Pepsi Crystal Pepsi to the competiti...,10-09-2024,167.0,584,833
4,zwerpw3wk320,user_9px5q0by,Reddit,My one week review of Coca-Cola Diet Coke: Bes...,31-05-2024,4749.0,152,630

In [14]:
df_2.shape

(12360, 8)

In [15]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12360 entries, 0 to 12359
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       12360 non-null  object
 1   user_id       12360 non-null  object
 2   platform      10514 non-null  object
 3   text_content  10614 non-null  object
 4   timestamp     12360 non-null  object
 5   likes         10502 non-null  float64
 6   shares        12360 non-null  int64
 7   comments      12360 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 772.6+ KB

In [16]:
df_2['likes'] = df_2['likes'].astype('Int64')

In [17]:
df_2.isnull().sum()

post_id            0
user_id            0
platform        1846
text_content    1746
timestamp          0
likes           1858
shares             0
comments           0
dtype: int64

In [18]:
dict = {'features': [], 'NaN%': []}
for feature in ['platform', 'text_content', 'likes']:
    dict['features'].append(feature)
    pct = df_2['platform'].isnull().sum()/df_2.shape[0]
    dict['NaN%'].append(f"{df_2[feature].isnull().sum()/df_2.shape[0] :.4f}")

In [19]:
null_df = pd.DataFrame(dict)
null_df

       features    NaN%
0      platform  0.1494
1  text_content  0.1413
2         likes  0.1503

In [20]:
df_2['platform'].fillna(df_2['platform'].mode()[0], inplace=True)

In [21]:
df_2['likes'].fillna(np.floor(df_2['likes'].mean()).astype('int'), inplace=True)

In [22]:
df_2['text_content'] = df_2['text_content'].fillna('No review')

In [23]:
df_2.isnull().sum()

post_id         0
user_id         0
platform        0
text_content    0
timestamp       0
likes           0
shares          0
comments        0
dtype: int64

In [24]:
df_2['text_content'] = df_2['text_content'].replace(r'^NULL.*','No review', regex=True)

In [25]:
df_2['timestamp'].unique()

array(['25-09-2024', '1722528840', '2025-04-13T20:12:18', ...,
       '2025-02-19T00:17:20', '1742309918', '2025-02-26T19:28:33'],
      dtype=object)

In [26]:
def convert_timestamp(t):
    t = str(t).strip()

    if t.isdigit():
        return pd.to_datetime(int(t), unit='s')

    return pd.to_datetime(t, dayfirst=True, errors='coerce')

In [27]:
df_2['timestamp'] = df_2['timestamp'].apply(convert_timestamp)

In [28]:
df_2.drop_duplicates(inplace=True)

In [29]:
df_2.shape

(12000, 8)

In [30]:
df_2.head()

,post_id,user_id,platform,text_content,timestamp,likes,shares,comments
0,to64mgey2v3y,user_vfxs1pry,Reddit,Bummed out with my new Air Max from Nike! Abso...,2024-09-25 00:00:00,4488,1456,673
1,7f0wdauzbj89,user_8l7rv5oe,Reddit,My one month review of Pepsi Crystal Pepsi: Hi...,2024-08-01 16:14:00,789,1484,39
2,dvvhg8eel45x,user_nfo3ih5u,YouTube,Just unboxed my new Highlander from Toyota. Ex...,2025-04-13 20:12:18,2247,1410,839
3,hgb9cxke4t7b,user_27aje6ur,Facebook,Comparing Pepsi Crystal Pepsi to the competiti...,2024-09-10 00:00:00,167,584,833
4,zwerpw3wk320,user_9px5q0by,Reddit,My one week review of Coca-Cola Diet Coke: Bes...,2024-05-31 00:00:00,4749,152,630

In [32]:
df_1.head()

         user_id          location language account_created  follower_count
0  user_guglt5jp   Berlin, Germany       ja      23-10-2023           38963
1  user_b1p3wz81   Munich, Germany       zh      06-05-2023           24644
2  user_jm2grmis        Dubai, UAE       en      03-01-2023           45842
3  user_ykoqww5l     Paris, France       fr      11-10-2023             665
4  user_3zzvv8vp  Los Angeles, USA       ru      23-05-2023           42908

In [33]:
df_1.to_csv("C:\Python\Corupted_system\Cleaned_data\Cleaned_Social_Engine_Users.csv", index=False)

In [34]:
df_2.to_csv("C:\Python\Corupted_system\Cleaned_data\Cleaned_Social_Engine_Posts.csv", index=False)